apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hikvision-doorbell
spec:
  parentRefs:
  - name: gateway
  hostnames:
  - doorbell-server.example.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: hikvision-doorbell-server
      port: 8080
